### ISSUE TITLE
Make Header and Footer links relative

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative2#150]
Part 1: Header links were fixed via https://github.com/hlxsites/merative2/pull/200 for the pages that are on Franklin. The pages that are not on Franklin should be left as links to www.merative.com.
Part 2: Footes -- Only 2 links as of 2023-05-30T13:07:45-04:00 are residing on Franklin, so the rest will be left as www.

**Comment by helms-charity** [comment]
It looks like this is an Authoring fix. 
![image](https://github.com/hlxsites/merative2/assets/3883795/9bc7dafc-3616-455a-9838-5b28e666394f)

**Comment by helms-charity** [comment]
Update: Scott Bridgemen started authoring the nav.docx per https://adobe-dx-support.slack.com/archives/C04BLPWJRGR/p1684761824492319

**Comment by helms-charity** [comment]
This is working as expected, but they still need to use www links for most of the footer since those pages are currently hosted on AEM.
