### ISSUE TITLE
Lighthouse: Incorrect aspect ratio for Related article card images

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative2#153]
Need to fix this score as reported for https://www.merative.com/blog
(report link: https://pagespeed.web.dev/analysis/https-www-merative-com-blog/i6wq4prr8x?form_factor=mobile )

**Image display dimensions should match natural aspect ratio. [Learn more about image aspect ratio](https://developer.chrome.com/docs/lighthouse/best-practices/image-aspect-ratio/?utm_source=lighthouse&utm_medium=lr).**

![image](https://github.com/hlxsites/merative2/assets/3883795/e012b8a1-a8cc-4e77-90ec-40537a3ba619)

Also, the Blog author image has the same problem:
![image](https://github.com/hlxsites/merative2/assets/3883795/ebcfcaa1-4755-4c40-89c5-296b598fe753)
https://pagespeed.web.dev/analysis/https-215-relatedeyebrow--merative2--hlxsites-hlx-page-blog-test-article/q8qbu1r4s6?utm_source=psi&utm_medium=redirect&form_factor=mobile

An optional opportunity for improvement: 
Lighthouse says we should set height and width sizes of the cards in the related-articles block cards.

![image](https://user-images.githubusercontent.com/3883795/232794429-8b215454-076e-46c0-8c9a-dcdb8b41ead9.png)

**Comment by helms-charity** [comment]
This might be helpful here https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

**Comment by Danielcodepad** [comment]
At a first glance, letting the height attribute of an image to fall back to 'auto' brings image display back to its natural aspect ratio.  I will research further whether this is applicable to other images or not.

<img width="851" alt="Screen Shot 2023-06-15 at 3 38 17 PM" src="https://github.com/hlxsites/merative2/assets/131390935/0ad2fc60-e9de-4348-adac-fe38b1a3e728">


<img width="837" alt="Screen Shot 2023-06-15 at 3 40 03 PM" src="https://github.com/hlxsites/merative2/assets/131390935/7aa41831-6e92-468f-bd42-ac3f9e0190a6">

**Comment by helms-charity** [comment]
That doesn't work, because the visible image dimensions must be maintained. This means a cropping of some sort needs to happen.
