### ISSUE TITLE
Incorrect column spacing in section bottom on homepage

### ISSUE THREAD

**Issue by arumsey** [hlxsites/merative2#156]
![image](https://github.com/hlxsites/merative2/assets/1004204/36086a71-8483-4447-a4da-9631839c2e6d)

Default margins between column elements are being used. Custom spacing may need to be added when `columns` is in a `section-bottom` section.

```
<div>
              <h1 id="32">32%</h1>
              <h4 id="decrease">DECREASE</h4>
              <p>in ED visits by high utilizers – Sonoma County, California</p>
</div>
```

According to [design](https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.com?type=design&node-id=428-43505&t=Oq6GtZ7hMmojODs0-0) this pattern should be based on stats.

**Comment by proeung** [comment]
@arumsey @helms-charity I just checked the column count/spacing for the large stat component used on the homepage and this issue looks to be fixed and in alignment with the design specs (see attached). Can you let me know if there's further action is needed for this issue, if not let's close it out.

![Screen Shot 2023-05-30 at 12 22 18 PM](https://github.com/hlxsites/merative2/assets/1815714/7d858697-f97f-42a4-b68e-d7e48cecc526)

**Mobile breakpoint**
![Screen Shot 2023-05-30 at 12 21 18 PM](https://github.com/hlxsites/merative2/assets/1815714/73281625-ac50-4344-bab3-b45768fb28db)

**Comment by helms-charity** [comment]
Sounds good to me, I will close it.
