### ISSUE TITLE
Ability to add a Blog Post subhead

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative2#172]
This is an item for the backlog and we'll need a design. 

We want the ability for content authors to have a blog sub head in their posts. Ideally, this would sit below the title of the blog and above the tags.

We should work with Ana to have the correct design for this.

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/111377779/217308213-02045d05-d65f-4601-a16d-85f6b7071b81.png">

UPDATE: 
Figma design link - https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.com?type=design&node-id=202%3A14&t=HCfNzvgD7e3QiiHU-1

**Comment by helms-charity** [comment]
Looks like there's a design, where the text is font size 24. 
https://www.figma.com/file/5N1U4VkQfWxw72KLGFwHcj/Blog-article-additions?type=design&node-id=624%3A4548&t=X2ZahHrXFwWo3wzS-1

So this can be an easy first issue for the Merative dev team. If we take this test page for example: https://main--merative2--hlxsites.hlx.page/blog/test-article-1
- The solution for authoring is a paragraph is added under the current page heading, nothing needed here.
- The solution for making that P text larger would be in the CSS, create a style for when the P is directly following the H1 only, and only on the Blog pages. 
![image](https://github.com/hlxsites/merative2/assets/3883795/b64cc199-e67b-451f-9370-f8702cd46e97)

**Comment by keith-kaplan** [comment]
@helms-charity looks like we'll need to add some styling here. I'm not seeing the blog topics show up above the image OR is that a seperate bug. 

This is the design for the blog subhead - https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.com?type=design&node-id=202%3A14&t=HCfNzvgD7e3QiiHU-1

Looking at the design it looks like the subhead is 16px below the Blog h1.
<img width="1120" alt="image" src="https://github.com/hlxsites/merative2/assets/111377779/fd4ed6fe-600d-4c30-b8c0-a0d17e176a7f">

**Comment by helms-charity** [comment]
Hmm, I will check the code to see if this is supposed to be showing but isn't. (I wasn't part of the phase 1 team so I don't recall seeing it). If it is part of the new design, then we'll make another ticket...

**Comment by helms-charity** [comment]
This ticket is a "To Do" for your dev team, by the way. I flagged it as a "good first issue" for them to look at.

**Comment by proeung** [comment]
Assigning this issue back to @helms-charity since she's working on #210 and will be adding the rendering of the subhead there.
