### ISSUE TITLE
Published Date Box

### ISSUE THREAD

**Issue by gboxmerative** [hlxsites/merative2#174]
Hi all,

We'd like to see a box in the metadata that lists a "Last Published On:" date where the user can enter a date. This will be good for articles that need frequent updating or reference specific data.

I'll reach out to Ana and see if I can get a mockup for this to include in this request.

**Comment by helms-charity** [comment]
@amol-anand do you know where you left off on this? I don't see "publication-date" in author-bio.js, but I see it is added to the index already.
![image](https://github.com/hlxsites/merative2/assets/3883795/d2a525b8-82e1-4084-820d-72b5b96f5238)

![image](https://github.com/hlxsites/merative2/assets/3883795/b51fce31-4545-41ea-b2c3-045aca93f2ca)
