### ISSUE TITLE
Create a tagging taxonomy hierarchy like the Adobe Blog

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative2#191]
We want to create a "pick your tag" spreadsheet like the Adobe blog for content authors. We have noticed inconsistencies in the topics/tags being used on blogs and some other pages. We'd like to use a solution like this or something similar to make keep tagging consistent.

https://main--blog--adobe.hlx.page/tools/tagger/index.html

<img width="2054" alt="image" src="https://github.com/hlxsites/merative2/assets/111377779/a6503574-89ee-4a01-9b37-74aa5e9ecd29">

**Comment by helms-charity** [comment]
Hi, This can be easily done - will put it on my list to find this feature from the Adobe project and get it into your site.

**Comment by helms-charity** [comment]
Progress update:
This is a WIP via https://github.com/hlxsites/merative2/tree/191-tagpicker. 
- I've only added in the initial files from the Adobe blog, 
- have not done any configurations special to Merative, 
- nor has this been connected to your actual content yet.

**Comment by keith-kaplan** [comment]
@helms-charity  just seeing this. Can you walk me through this real quick?
