### ISSUE TITLE
feat: sort blog home cards by publication-date

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative2#219]
Currently, the cards on the blog homepage are sorted by lastModified date.
Feature request: Use the manually-entered "publication-date" from the articles' metadata table to sort by. 
I think we could still use "lastModified" as an ELSE IF there is no publication-date authored.

@amol-anand suggests: Remove the sort in the code altogether and in the blog/query-index we can have a sheet (that replicates whatever is in the raw_data sheet but sorts by publish date) then we always get the json in sorted order. That way if in the future we want to change the order to something else, we can just deal with that in the index sheet and no need for a code change.

**Comment by Danielcodepad** [comment]
WIP
