### ISSUE TITLE
Bug: Homepage linear-gradient in iphone Safari

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative2#228]
The linear gradient isn't properly rendering in ios Safari the way it is when emulating via browser.

![image](https://github.com/hlxsites/merative2/assets/3883795/fc770572-14bb-487a-8ba2-4b407fb056d2)

**Comment by proeung** [comment]
Looks like we're using a linear gradient within Franklin to render the curve. This method doesn't yield consistent results on all browsers, especially on Safari mobile. We might need to switch to using SVG, which looks to be what we were using on the AEM version of the homepage (https://author-p65153-e554352.adobeaemcloud.com/content/merative/us/en.html?wcmmode=disabled).
