### ISSUE TITLE
Update CSP to allow for Hotjar Script

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative2#230]
**JIRA ticket:** https://jira.wh-sdlc.watson-health.ibm.com/browse/MERATIVE-757

### Problem

We purchased a Hotjar license for heat mapping tracking, but our CSP on Franklin and AEM blocks the script from loading.

### Solution

Update both CSPs on Franklin and AEM to allow Hotjar to load properly. See below for requirements.

https://help.hotjar.com/hc/en-us/articles/115011640307-Content-Security-Policies

### Requirements

Existing CSP - https://github.com/hlxsites/merative2/blob/main/head.html

`<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.mktoweb.com rum.hlx.page *.googletagmanager.com js.zi-scripts.com *.zoominfo.com *.merative.com *.salesloft.com *.googleadservices.com *.kryogenix.org *.adsrvr.org www.youtube.com cm.everesttech.net documentservices.adobe.com googleads.g.doubleclick.net assets.adobedtm.com merative.tt.omtrdc.net cdn.jsdelivr.net dpm.demdex.net munchkin.marketo.net rtp-static.marketo.com sjrtp7.marketo.com cdn.cookielaw.org resources.digital-cloud-west.medallia.com *.kampyle.com js.driftt.com; img-src 'self' data: *.merative.com *.mktoweb.com *.google.co.in *.google.com *.google.ca *.googletagmanager.com *.112.2o7.net *.ytimg.com assets.adobedtm.com dpm.demdex.net cdn.cookielaw.org cm.everesttech.net *.medallia.com *.kampyle.com; frame-src 'self' *.mktoweb.com *.navattic.com *.adsrvr.org www.youtube.com player.vimeo.com *.merative.com documentservices.adobe.com merative.demdex.net *.medallia.com *.kampyle.com js.driftt.com; connect-src 'self' rum.hlx.page *.mktoweb.com *.mktoresp.com *.marketo.com *.salesloft.com js.zi-scripts.com *.zoominfo.com *.adsrvr.org *.112.2o7.net assets.adobedtm.com viewlicense.adobe.io *.onetrust.com merative.tt.omtrdc.net analytics.google.com stats.g.doubleclick.net dpm.demdex.net cdn.cookielaw.org *.medallia.com *.kampyle.com; style-src 'self' 'unsafe-inline' *.mktoweb.com *.marketo.com go.merative.com assets.adobedtm.com cdn.cookielaw.org *.medallia.com *.kampyle.com; font-src 'self' *.mktoweb.com assets.adobedtm.com cdn.cookielaw.org *.medallia.com *.kampyle.com; object-src 'none'; manifest-src 'self'; media-src 'self' *.merative.com; worker-src 'none';"> `

### Updated CSP

`<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.mktoweb.com rum.hlx.page *.googletagmanager.com js.zi-scripts.com *.zoominfo.com *.merative.com *.salesloft.com *.googleadservices.com *.kryogenix.org *.adsrvr.org www.youtube.com cm.everesttech.net documentservices.adobe.com googleads.g.doubleclick.net assets.adobedtm.com merative.tt.omtrdc.net cdn.jsdelivr.net dpm.demdex.net munchkin.marketo.net rtp-static.marketo.com sjrtp7.marketo.com cdn.cookielaw.org resources.digital-cloud-west.medallia.com *.kampyle.com js.driftt.com *.hotjar.com; img-src 'self' data: *.merative.com *.mktoweb.com *.google.co.in *.google.com *.google.ca *.googletagmanager.com *.112.2o7.net *.ytimg.com assets.adobedtm.com dpm.demdex.net cdn.cookielaw.org cm.everesttech.net *.medallia.com *.kampyle.com *.hotjar.com; frame-src 'self' *.mktoweb.com *.navattic.com *.adsrvr.org www.youtube.com player.vimeo.com *.merative.com documentservices.adobe.com merative.demdex.net *.medallia.com *.kampyle.com js.driftt.com; connect-src 'self' rum.hlx.page *.mktoweb.com *.mktoresp.com *.marketo.com *.salesloft.com js.zi-scripts.com *.zoominfo.com *.adsrvr.org *.112.2o7.net assets.adobedtm.com viewlicense.adobe.io *.onetrust.com merative.tt.omtrdc.net analytics.google.com stats.g.doubleclick.net dpm.demdex.net cdn.cookielaw.org *.medallia.com *.kampyle.com *.hotjar.com *.hotjar.io; style-src 'self' 'unsafe-inline' *.mktoweb.com *.marketo.com go.merative.com assets.adobedtm.com cdn.cookielaw.org *.medallia.com *.kampyle.com *.hotjar.com; font-src 'self' *.mktoweb.com assets.adobedtm.com cdn.cookielaw.org *.medallia.com *.kampyle.com *.hotjar.com; object-src 'none'; manifest-src 'self'; media-src 'self' *.merative.com; worker-src 'none';"> ` 

### Testing

A member of the digital team will test webpages using AEM Platform debugger to ensure launch rules are loading correctly and installation works.

**Comment by helms-charity** [comment]
@proeung @keith-kaplan it looks like this was done, can we close the ticket?

**Comment by keith-kaplan** [comment]
Yes, let's close it.
