### ISSUE TITLE
Upgrade block library to use new plugin

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative2#239]
Currently we have a block library that is feature rich. 

There is a new Sidekick library plugin project that has a lot more features that we should migrate to to make it easy for authors to create content 
Code: https://github.com/adobe/franklin-sidekick-library
Preview: https://main--rosalind-boilerplate--dylandepass.hlx.live/tools/sidekick/library.html?plugin=blocks

**Comment by helms-charity** [comment]
Ooh this looks slick, I will refrain from library updates until you've added it in.
