### ISSUE TITLE
authoring: /curam

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative2#259]
a.k.a. Health and Human services. Needs authoring.

Live site:
https://www.merative.com/curam

Figma design:
https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.com?type=design&node-id=202%3A44111&mode=design&t=PNLkzKvRao67kFbF-1

There is no current Word doc yet.

**Comment by proeung** [comment]
@helms-charity Can you let me know why this issue is needed? `/curam` is a page that's being managed in AEM.

**Comment by helms-charity** [comment]
Unless I'm mistaken, I believe this page had another name originally and that page was part of "phase 3" migration. So I deduced that this page would need to be created in Franklin instead of the 'other' page.
cc: @keith-kaplan
