### ISSUE TITLE
Implement new "Content band checkmarks" section/pattern

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative2#276]
## Problems/Motivation

- This ticket is part of the phase 3 effort, which is to migrate all of the remaining components/patterns in AEM over to Franklin. See EPIC for more detail (MERATIVE-765)
- Section > Section Content band checkmarks
- Note: part of this work is to clean up the naming in Franklin to ensure it aligns with our Design Systems.

## Sharepoint Doc Structure

- https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7BC32AC9D0-6DF0-4720-A997-A30236C6CEDF%7D&file=section-content-band-checkmarks.docx&action=default&mobileredirect=true&cid=f46d268f-57e8-43fd-b154-1f67521ddb11
- https://main--merative2--hlxsites.hlx.page/block-library/sections/section-content-band-checkmarks
- Need to create a new section for this called "Section content band checkmarks"
- Variations needed white background and bone background

## Design/Specs

- Figma link - https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=1459%3A12919&mode=design&t=0mcFm2zGMxvLkL3D-1

![image](https://github.com/hlxsites/merative2/assets/111377779/701c301c-a99c-4b4e-80cd-2789e392f479)

## Dev Checklist

- Open a PR on the Franklin repo project - https://github.com/hlxsites/merative2 
- Follow the PR template and include written testing instructions
- Once, the PR has been merged, make sure to update "Block Library" (see link) to include the block content entry structure for this variation.

Corresponding JIRA ticket
- https://jira.sdlc.merative.com/browse/MERATIVE-780

**Comment by helms-charity** [comment]
I saw someone was working on a block-library page, but I see it need some style help.
https://239-sidekickupgrade--merative2--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/sections/section-content-band-checkmarks&index=1

**Comment by helms-charity** [comment]
![image](https://github.com/hlxsites/merative2/assets/3883795/f30335f8-1560-42ca-92fd-938a968d6ce9)

**Comment by keith-kaplan** [comment]
Thanks @helms-charity . @nimithshetty17  is working on this one and will open a PR for this when ready.
