### ISSUE TITLE
Implement new "Carousel - Case study" block/pattern

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative2#278]
## Problems/Motivation

- This ticket is part of the phase 3 effort, which is to migrate all of the remaining components/patterns in AEM over to Franklin. See EPIC for more detail ([MERATIVE-765](https://jira.sdlc.merative.com/browse/MERATIVE-765))
- Blocks > Carousel
- There's already a block in Franklin called "Carousel" - https://main--merative2--hlxsites.hlx.page/block-library/blocks/carousel 
- This will be a variation called "Carousel - Case Study"
- Note: part of this work is to clean up the naming in Franklin to ensure it aligns with our Design Systems.

## Sharepoint Doc Structure

- Case study carousel variation added to carousel block https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B384FABF7-5FA8-4D8F-B031-976CFB6C1C4A%7D&file=carousel.docx&action=default&mobileredirect=true
- https://main--merative2--hlxsites.hlx.page/block-library/blocks/carousel

## Design/Specs

Figma link - https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=1634%3A13852&mode=design&t=leAsxbNftxoq6gTd-1 
<img width="768" alt="image" src="https://github.com/hlxsites/merative2/assets/111377779/e8d8906f-eebb-44c3-ae73-c8b4d673f61e">

## Dev Checklist

- Open a PR on the Franklin repo project - https://github.com/hlxsites/merative2 
- Follow the PR template and include written testing instructions
- Once, the PR has been merged, make sure to update "Block Library" (see [link](https://merative.sharepoint.com/sites/Merative.comWebsite/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FMerative%2EcomWebsite%2FShared%20Documents%2Fwebsite%2Fblock%2Dlibrary&viewid=472996a8%2Df9ce%2D49f3%2Da65d%2Dfa8f62592c02)) to include the block content entry structure for this variation.

Corresponding JIRA ticket
- https://jira.sdlc.merative.com/browse/MERATIVE-785

**Comment by helms-charity** [comment]
@keith-kaplan is there a live page on AEM you can link to where I can see this in action?

**Comment by keith-kaplan** [comment]
@helms-charity  this is a net new block. It was never developed in AEM Sites for us.
