### ISSUE TITLE
Implement new "Image band - flush bottom" Section/pattern

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative2#283]
## Problems/Motivation

- This ticket is part of the phase 3 effort, which is to migrate all of the remaining components/patterns in AEM over to Franklin. See EPIC for more detail ([MERATIVE-765](https://jira.sdlc.merative.com/browse/MERATIVE-765))
- Section > Image band - flush bottom
- Note: part of this work is to clean up the naming in Franklin to ensure it aligns with our Design Systems.

## Sharepoint Doc Structure

- [https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B099E2636-0468-4B35-9110-22FC954245D1%7D&file=section-image-band-flush-bottom.docx&action=default&mobileredirect=true](https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B6F7B5361-601C-40B0-80A7-4AB93A8F378C%7D&file=section-content-band-list.docx&action=default&mobileredirect=true)
- https://main--merative2--hlxsites.hlx.page/block-library/sections/section-image-band-flush-bottom
- Need to create a new section and variations for this called "Image band - flush bottom"

## Design/Specs

- Figma link - https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=1459%3A19541&mode=design&t=IsiigUvRGTcztZ7I-1
- 
<img width="792" alt="image" src="https://github.com/hlxsites/merative2/assets/111377779/bfcff871-f797-405e-add3-ca8d8b9a8590">

## Dev Checklist

- Open a PR on the Franklin repo project - https://github.com/hlxsites/merative2 
- Follow the PR template and include written testing instructions
- Once, the PR has been merged, make sure to update "Block Library" (see [link](https://merative.sharepoint.com/sites/Merative.comWebsite/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FMerative%2EcomWebsite%2FShared%20Documents%2Fwebsite%2Fblock%2Dlibrary&viewid=472996a8%2Df9ce%2D49f3%2Da65d%2Dfa8f62592c02)) to include the block content entry structure for this variation.

Corresponding JIRA ticket
- https://jira.sdlc.merative.com/browse/MERATIVE-782

**Comment by helms-charity** [comment]
Is there a live AEM link to this you can share, or is it brand new?
