### ISSUE TITLE
Implement new "Overview" block/pattern

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative2#284]
## Problems/Motivation

- We added a new component/pattern to the Design System called "Overview".
- There's already a block in Franklin called "Column" - https://main--merative2--hlxsites.hlx.page/block-library/blocks/columns 
- Note: part of this work is to clean up the naming in Franklin to ensure it aligns with our Design Systems.

## Sharepoint Doc Structure

- https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7BA9F343B6-E86F-44AF-AA82-C770A03655AE%7D&file=section-overview.docx&action=default&mobileredirect=true
- https://main--merative2--hlxsites.hlx.page/block-library/sections/section-overview
- New section called "Section Overview" is needed with variations for three column and two columns

## Design/Specs

Figma link - https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=14301%3A70524&mode=design&t=IsiigUvRGTcztZ7I-1

![Overview 3 - desktop](https://github.com/hlxsites/merative2/assets/111377779/109b6b3a-6435-41a9-a206-8b5cfbf1fa28)

![Overview 2 - desktop](https://github.com/hlxsites/merative2/assets/111377779/6eb1d4f3-ba73-400a-8249-5e998f90b03d)

## Dev Checklist

- Open a PR on the Franklin repo project - https://github.com/hlxsites/merative2 
- Follow the PR template and include written testing instructions
- Once, the PR has been merged, make sure to update "Block Library" (see [link](https://merative.sharepoint.com/sites/Merative.comWebsite/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FMerative%2EcomWebsite%2FShared%20Documents%2Fwebsite%2Fblock%2Dlibrary&viewid=472996a8%2Df9ce%2D49f3%2Da65d%2Dfa8f62592c02)) to include the block content entry structure for this variation.

Corresponding JIRA ticket
- https://jira.sdlc.merative.com/browse/MERATIVE-651

**Comment by helms-charity** [comment]
@keith-kaplan this has been added to the new sidekick as a section that users can copy and paste onto their new page. 
You can try it out at https://239-sidekickupgrade--merative2--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/sections/section-overviewtest&index=0 .
I will keep this ticket open while my PR is still under review for #239 .
![image](https://github.com/hlxsites/merative2/assets/3883795/98ed7d85-d9aa-43a2-8bd5-ad7fcd86251a)

**Comment by keith-kaplan** [comment]
Thanks, @helms-charity  this request was part of the phase 3 work some of our team members were going to do. I'm glad you grabbed this one and moved it forward.
