### ISSUE TITLE
Merative homepage displaying incorrectly on Microsoft edge

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative2#287]
We have received a few users reports that the Merative homepage is not displaying correctly when viewed in an Edge browser on a Windows machine. Can we look into why this is happening and provide a fix.

![image](https://github.com/hlxsites/merative2/assets/111377779/a1e1ca10-2fb1-4b7d-991e-a4ba2134f30d)

URL - www.merative.com
Jira issue - https://jira.sdlc.merative.com/browse/MERATIVE-794
Browser - Edge
Version - Version 114.0.1823.82 (Official build) (64-bit)

**Comment by helms-charity** [comment]
Even after updating to Version 114.0.1823.86 everything is looking good for me.

**Comment by keith-kaplan** [comment]
Thanks. Let me ask a team member that has edge if they're still seeing it.

**Comment by keith-kaplan** [comment]
Confirmed with team member and they are not seeing issue anymore. Can close this.
